framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        excluded_patterns:
            - '*/tests/*'
            - '*/node_modules/*'

        # Configuration pour les imports ES6
        importmap_path: '%kernel.project_dir%/importmap.php'

        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
